### PR TITLE
refactor: Refactor ConstantContainer into separate classes and add Containers class

### PR DESCRIPTION
**Pull request by tangcent**
Refactors the ConstantContainer class into three separate classes: ConstantContainerBuilder, EnumContainerBuilder, and ImmutableMapContainer. The code for each class has been moved to its own file in the same package.

In addition, a new Containers class has been added that provides a factory method for creating instances of the different container classes from various data sources, such as Map, Enum, or Constant.

### CODE REVIEW

**Comment by Createsequence** [comment]
Reasonable improvements.

Based on the current situation, `EnumContainer` and `ConstantContainer` do not seem to be necessary to continue to retain, because they have become the factory class of `ImmutableMapContainer`, this responsibility is repeated with the static factory of `Containers`.
Therefore, from a personal point of view, the `EnumContainer `and `ConstantContainer `classes can be removed and the static factory methods they have should be merged into `Containers`.

**Comment by tangcent** [comment]
This is exactly what I hesitate. If `EnumContainer` and `ConstantContainer` be merged into `Containers`, the `Containers` may become too complicated.
As a user, I want to simply use `Containers` to create all Containers what I want.  However, as a writer, I may prefer to encapsulate the code responsible for creating the container using enums within `EnumContainer`. Similarly, the code that generates a container from constants is enclosed within `ConstantContainer`.
In general, I prefer to use `Containers`. I will make the changes.

**Comment by tangcent** [comment]
@Createsequence PTAL

**Comment by Createsequence** [comment]
impeccable PR, beautifully done :)

**Pull request merged**
